version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: .dockerfile
    volumes:
    - ./backend:/usr/app/backend
    - /usr/app/backend/node_modules
    ports:
    - 3333:3333
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: tuttecose
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: tuttecose