version: '3.8'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: .dockerfile
    depends_on:
      - mysql
    ports:
      - 3333:3333
    environment:
      - VIRTUAL_HOST=tuttecose.loc
      - VIRTUAL_PORT=3333
    volumes:
      - ./backend:/usr/app/backend
      - /usr/app/backend/node_modules

  mysql:
    container_name: mysql
    image: mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: tuttecose
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: tuttecose